import { ConfigFields } from "@/types/configFields";

export const configFields: ConfigFields = [
  {
    name: "temperature",
    type: "spinbox_slider",
    title: "Temperature",
    description: "The temperature of the widget",
    min: 0,
    step: 0.25,
  },
  {
    name: "top_p",
    type: "spinbox",
    title: "Top P",
    description: "The top p of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 1,
  },
  {
    name: "top_k",
    type: "spinbox",
    title: "Top K",
    description: "The top k of the widget",
    min: 0,
    max: 200,
    step: 10,
    default: 50,
  },
  {
    name: "min_p",
    type: "spinbox_slider",
    title: "Min P",
    description: "The min p of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 0,
  },
  {
    name: "top_a",
    type: "spinbox",
    title: "Top A",
    description: "The top a of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 0,
  },
  {
    name: "frequency_penalty",
    type: "spinbox",
    title: "Frequency Penalty",
    description: "The frequency penalty of the widget",
    min: -2,
    max: 2,
    step: 0.25,
    default: 0,
  },
  {
    name: "presence_penalty",
    type: "spinbox",
    title: "Presence Penalty",
    description: "The presence penalty of the widget",
    min: -2,
    max: 2,
    step: 0.25,
    default: 0,
  },
  {
    name: "repetition_penalty",
    type: "spinbox",
    title: "Repetition Penalty",
    description: "The repetition penalty of the widget",
    min: 1,
    max: 3,
    step: 0.25,
    default: 1,
  },
  {
    name: "seed",
    type: "random_number",
    title: "Seed",
    description: "The seed of the widget",
    min: -1,
    max: 1000000000,
    default: -1,
  },
  {
    name: "smoothing_sampling",
    type: "section",
    title: "Smooth Sampling",
    description: "The smooth sampling of the widget",
    fields: [
      {
        name: "smoothing_factor",
        type: "spinbox",
        title: "Smooth Factor",
        description: "The smooth factor of the widget",
        min: 0,
        max: 10,
        step: 0.15,
        default: 0,
      },
      {
        name: "smoothing_curve",
        type: "spinbox",
        title: "Smooth Curve",
        description: "The smooth curve of the widget",
        min: 1,
        max: 10,
        step: 0.5,
        default: 1,
      },
    ],
  },
  {
    name: "dry",
    type: "section",
    title: "Dry Repetition Penalty",
    description: "The dry repetition penalty of the widget",
    fields: [
      {
        name: "dry_multiplier",
        type: "spinbox_slider",
        title: "Multiplier",
        description: "The dry multiplier of the widget",
        min: 0,
        max: 5,
        default: 0,
        step: 0.1,
      },
      {
        name: "dry_base",
        type: "spinbox",
        title: "Base",
        description: "The dry base of the widget",
        min: 1,
        max: 4,
        default: 1.75,
        step: 0.15,
      },
      {
        name: "dry_allowed_length",
        type: "spinbox", 
        title: "Allowed Length",
        description: "Maximum allowed length of repeated sequences",
        min: 0,
        max: 20,
        default: 0,
        step: 1,
      },
      {
        name: "dry_penalty_last_n",
        type: "spinbox",
        title: "Penalty Range",
        description: "Number of tokens to look back for repetition penalty",
        min: 0,
        max: 2048,
        default: 512,
        step: 64,
      },
      {
        name: "dry_sequence_breakers",
        type: "string_array",
        title: "Sequence Breakers",
        description: "Sequence breakers for dry repetition penalty",
        default: ["\n", ":", "\"", "*"],
      }
    ],
  },
  {
    name: "xtc",
    type: "section",
    title: "Exclude Top Choices (XTC)",
    description: "XTC settings for token sampling",
    fields: [
      {
        name: "xtc_threshold",
        type: "spinbox_slider",
        title: "Threshold",
        description: "Number of top tokens to exclude from sampling",
        min: 0,
        max: 0.5,
        default: 0.1,
        step: 0.05
      },
      {
        name: "xtc_probability", 
        type: "spinbox_slider",
        title: "Probability",
        description: "Probability of applying XTC during sampling",
        min: 0,
        max: 1,
        default: 0,
        step: 0.05
      }
    ]
  }
  ,
  {
    name: "sampling_order",
    type: "drag_array",
    title: "Sampling Order",
    description: "Drag to reorder the sampling methods",
    default: ["dry", "xtc", "min_p", "top_p", "top_k", "temperature"],
    options: ["dry", "xtc", "min_p", "top_p", "top_k", "temperature"],
    readOnly: true
  }
];

