import { ConfigFields } from "@/schema/template-chat-settings-types";

export const configFields: ConfigFields = [
  {
    name: "temperature",
    type: "stepbutton_slider",
    title: "Temperature",
    description: "The temperature of the widget",
    min: 0,
    max: 5,
    step: 0.25,
  },
  {
    name: "top_p",
    type: "stepbutton",
    title: "Top P",
    description: "The top p of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 1,
  },
  {
    name: "top_k",
    type: "stepbutton",
    title: "Top K",
    description: "The top k of the widget",
    min: 0,
    max: 200,
    step: 10,
    default: 50,
  },
  {
    name: "min_p",
    type: "stepbutton_slider",
    title: "Min P",
    description: "The min p of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 0,
  },
  {
    name: "top_a",
    type: "stepbutton",
    title: "Top A",
    description: "The top a of the widget",
    min: 0,
    max: 1,
    step: 0.25,
    default: 0,
  },
  {
    name: "frequency_penalty",
    type: "stepbutton",
    title: "Frequency Penalty",
    description: "The frequency penalty of the widget",
    min: -2,
    max: 2,
    step: 0.25,
    default: 0,
  },
  {
    name: "presence_penalty",
    type: "stepbutton",
    title: "Presence Penalty",
    description: "The presence penalty of the widget",
    min: -2,
    max: 2,
    step: 0.25,
    default: 0,
  },
  {
    name: "repetition_penalty",
    type: "stepbutton",
    title: "Repetition Penalty",
    description: "The repetition penalty of the widget",
    min: 1,
    max: 3,
    step: 0.25,
    default: 1,
  },
  {
    name: "seed",
    type: "random_number",
    title: "Seed",
    description: "The seed of the widget",
    min: -1,
    max: 1000000000,
    default: -1,
  },
  {
    name: "smoothing_sampling",
    type: "section",
    title: "Smooth Sampling",
    description: "The smooth sampling of the widget",
    fields: [
      {
        name: "smoothing_factor",
        type: "stepbutton",
        title: "Smooth Factor",
        description: "The smooth factor of the widget",
        min: 0,
        max: 10,
        step: 0.15,
        default: 0,
      },
      {
        name: "smoothing_curve",
        type: "stepbutton",
        title: "Smooth Curve",
        description: "The smooth curve of the widget",
        min: 1,
        max: 10,
        step: 0.5,
        default: 1,
      },
    ],
  },
  {
    name: "dry",
    type: "section",
    title: "Dry Repetition Penalty",
    description: "The dry repetition penalty of the widget",
    fields: [
      {
        name: "dry_multiplier",
        type: "stepbutton_slider",
        title: "Multiplier",
        description: "The dry multiplier of the widget",
        min: 0,
        max: 5,
        default: 0,
        step: 0.1,
      },
      {
        name: "dry_base",
        type: "stepbutton",
        title: "Base",
        description: "The dry base of the widget",
        min: 1,
        max: 4,
        default: 1.75,
        step: 0.15,
      },
      {
        name: "dry_allowed_length",
        type: "stepbutton",
        title: "Allowed Length",
        description: "Maximum allowed length of repeated sequences",
        min: 0,
        max: 20,
        default: 0,
        step: 1,
      },
      {
        name: "dry_penalty_last_n",
        type: "stepbutton",
        title: "Penalty Range",
        description: "Number of tokens to look back for repetition penalty",
        min: 0,
        max: 2048,
        default: 512,
        step: 64,
      },
      {
        name: "dry_sequence_breakers",
        type: "string_array",
        title: "Sequence Breakers",
        description: "Sequence breakers for dry repetition penalty",
        default: ["\\n", ":", '"', "*"],
      },
    ],
  },
  {
    name: "xtc",
    type: "section",
    title: "Exclude Top Choices (XTC)",
    description: "XTC settings for token sampling",
    fields: [
      {
        name: "xtc_threshold",
        type: "stepbutton_slider",
        title: "Threshold",
        description: "Number of top tokens to exclude from sampling",
        min: 0,
        max: 0.5,
        default: 0.1,
        step: 0.05,
      },
      {
        name: "xtc_probability",
        type: "stepbutton_slider",
        title: "Probability",
        description: "Probability of applying XTC during sampling",
        min: 0,
        max: 1,
        default: 0,
        step: 0.05,
      },
    ],
  },
  {
    name: "sampling_order",
    type: "drag_array",
    title: "Sampling Order",
    description: "Drag to reorder the sampling methods",
    default: ["dry", "xtc", "min_p", "top_p", "top_k", "temperature"],
    options: ["dry", "xtc", "min_p", "top_p", "top_k", "temperature"],
    readOnly: true,
  },
  {
    name: "reasoning",
    type: "section",
    title: "Reasoning",
    description: "Enable Reasoning. Reasoning in most models will disable any other sampling methods.",
    fields: [
      {
        name: "reasoning_budget",
        type: "stepbutton",
        title: "Reasoning Budget",
        description: "The reasoning budget of the widget. Affect Anthropic and some models.",
        min: 0,
        max: 63999,
        step: 1024,
        default: 1024,
      },
      {
        name: "reasoning_temperature",
        type: "stepbutton_slider",
        title: "Reasoning Effort (3=High)",
        description: "The effort of the reasoning. Affect OpenAI and some models.",
        min: 1,
        max: 3,
        step: 1,
        default: 1,
      },
    ],
  },
  {
    name: "prompt_cache",
    type: "section",
    title: "Prompt Cache",
    description: "Enable Prompt Cache. Affect Anthropic and some models.",
    fields: [
      {
        name: "chat_depth",
        type: "stepbutton",
        title: "Chat Depth",
        description: "Maximum number of messages to cache",
        min: 0,
        max: 50,
        step: 1,
        default: 0,
      },
    ],
  },
];
